//
//  MovieListPresenter.swift
//  TMDB
//
//  Created by ankit on 15/07/17.
//  Copyright (c) 2017 test. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListPresentationLogic
{
    func presentFetchedMovies(response : MovieList.FetchMovieList.Response)
    func presentInsertedMovie(response : MovieList.InsertedMovie.Response)
}

class MovieListPresenter: MovieListPresentationLogic
{
    weak var viewController: MovieListDisplayLogic?
    
    func presentFetchedMovies(response : MovieList.FetchMovieList.Response){
        if let unWrappedError = response.error{
            let viewModel = MovieList.FetchMovieList.ViewModel(errorMsg: unWrappedError)
            viewController?.displayFetchedError(viewModel: viewModel)
        }
    }
    
    func presentInsertedMovie(response : MovieList.InsertedMovie.Response){
        let movie =  response.formatteMovie
        viewController?.insertMovie(viewModel: MovieList.InsertedMovie.ViewModel(
            movieTitle: movie.title,
            posterURL: movie.posterURL,
            releaseYear: movie.releaseYear,
            indexPath: response.indexPath
        ))
    }
    
    
}
