//
//  MovieListModels.swift
//  TMDB
//
//  Created by ankit on 15/07/17.
//  Copyright (c) 2017 test. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieList
{
    // MARK: Use cases
    
    enum FetchMovieList {
        struct Request
        {
            var pageNumber : Int
            init(pageNumber : Int) {
                self.pageNumber = pageNumber
            }
        }
        struct Response
        {
            var error : String?
        }
        struct ViewModel
        {
            var errorMsg : String?
        }
    }
    enum InsertedMovie {
        struct Request {
            
        }
        struct Response {
            var formatteMovie : Movie
            var indexPath : IndexPath
        }
        struct ViewModel {
            var movieTitle : String
            var posterURL : URL?
            var releaseYear : Int
            var indexPath : IndexPath
        }
        
    }
    enum DisplayPosterImage
    {
        struct Request
        {
            var poasteImageURL : URL?
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum ApplyPredicate
    {
        struct Request
        {
            var generatedPredicate : NSPredicate?
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }

    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
